import type { RoadmapDefinition } from "../types";

export const angularRoadmap: RoadmapDefinition = {
  slug: "angular",
  title: "Angular Developer Roadmap",
  subtitle: "Master Standalone Components, Signals, Router, Typed Forms, and Enterprise Architecture",
  description:
    "Comprehensive guide to modern Angular: from CLI setup to standalone components, Signals reactivity, functional guards, RxJS, and enterprise hydration.",
  category: "framework",
  featured: false,
  icon: "code",
  level: "Beginner → Production",
  estimatedDuration: "4 - 6 Months",
  relatedRoadmaps: ["frontend", "typescript", "full-stack"],
  sections: [
    { id: "setup", title: "1. Angular CLI & Architecture", order: 1 },
    { id: "components", title: "2. Components, Templates & Control Flow", order: 2 },
    { id: "signals", title: "3. Signals & Fine-Grained Reactivity", order: 3 },
    { id: "routing", title: "4. Angular Router & Functional Guards", order: 4 },
    { id: "forms", title: "5. Reactive Forms & Validation", order: 5 },
    { id: "http", title: "6. HttpClient & Interceptors", order: 6 },
  ],
  nodes: [
    {
      id: "ng-overview",
      title: "Angular Overview & Standalone Architecture",
      description: "Standalone components, modern project structure, and eliminating NgModules.",
      docsHref: "/docs/angular/angular-overview",
      type: "primary",
      level: "beginner",
      sectionId: "setup",
      keyConcepts: ["Standalone Components", "ng new CLI", "app.config.ts"],
    },
    {
      id: "ng-components",
      title: "Components & Template Control Flow",
      description: "Modern template syntax: @if, @for, @switch, and signal inputs/outputs.",
      docsHref: "/docs/angular/components",
      type: "primary",
      level: "beginner",
      sectionId: "components",
      keyConcepts: ["@if and @for Blocks", "Signal Inputs (input())", "Signal Outputs (output())"],
    },
    {
      id: "ng-signals",
      title: "Angular Signals & Reactivity",
      description: "Writable signals (signal()), computed derived state, and effect() side effects.",
      docsHref: "/docs/angular/signals",
      type: "primary",
      level: "intermediate",
      sectionId: "signals",
      keyConcepts: ["signal() & update()", "computed() Memoization", "effect() Cleanup"],
    },
    {
      id: "ng-routing",
      title: "Angular Router & Navigation",
      description: "Configuring routes, lazy-loaded components, route parameters, and auth guards.",
      docsHref: "/docs/angular/routing",
      type: "primary",
      level: "intermediate",
      sectionId: "routing",
      keyConcepts: ["loadComponent()", "Functional canActivate Guard", "RouterLink"],
    },
    {
      id: "ng-forms",
      title: "Reactive Forms & Typed Validation",
      description: "FormGroup, FormControl, FormBuilder, custom validators, and dynamic inputs.",
      docsHref: "/docs/angular/forms",
      type: "primary",
      level: "intermediate",
      sectionId: "forms",
      keyConcepts: ["FormBuilder", "Validators.required", "ReactiveFormsModule"],
    },
    {
      id: "ng-http",
      title: "HttpClient & Functional Interceptors",
      description: "Type-safe API requests, bearer token injection, and global error handling.",
      docsHref: "/docs/angular/http-client",
      type: "primary",
      level: "intermediate",
      sectionId: "http",
      keyConcepts: ["provideHttpClient()", "HttpInterceptorFn", "RxJS / Signals Bridge"],
    },
  ],
  edges: [
    { source: "ng-overview", target: "ng-components", type: "primary" },
    { source: "ng-components", target: "ng-signals", type: "primary" },
    { source: "ng-signals", target: "ng-routing", type: "primary" },
    { source: "ng-routing", target: "ng-forms", type: "primary" },
    { source: "ng-forms", target: "ng-http", type: "primary" },
  ],
};
