import type { RoadmapDefinition } from "../types";

export const backendRoadmap: RoadmapDefinition = {
  slug: "backend",
  title: "Backend Developer Roadmap",
  subtitle: "Step-by-step path to architecting high-throughput, secure, distributed backend systems",
  description:
    "Master Linux server administration, Node.js & Go runtimes, relational PostgreSQL modeling, caching with Redis, authentication security, Docker, and distributed APIs.",
  category: "role",
  featured: true,
  icon: "server",
  level: "Beginner → Production",
  estimatedDuration: "8 - 12 Months",
  relatedRoadmaps: ["nodejs", "linux", "postgresql", "docker", "networking", "full-stack", "devops"],
  sections: [
    { id: "protocols", title: "1. Networking Protocols & Internet", order: 1 },
    { id: "linux", title: "2. Linux Server & Shell Administration", order: 2 },
    { id: "language", title: "3. Backend Language & Runtime", order: 3 },
    { id: "api-design", title: "4. RESTful & GraphQL API Architecture", order: 4 },
    { id: "databases", title: "5. Relational Databases & PostgreSQL", order: 5 },
    { id: "orms", title: "6. ORMs & Query Builders (Prisma)", order: 6 },
    { id: "auth", title: "7. Authentication & Security (AuthN/AuthZ)", order: 7 },
    { id: "caching", title: "8. Caching & In-Memory Stores", order: 8 },
    { id: "containers", title: "9. Docker & Server Deployment", order: 9 },
    { id: "production", title: "10. Scalability & System Design", order: 10 },
  ],
  nodes: [
    // Section 1: Protocols
    {
      id: "be-http-dns",
      title: "HTTP/2, HTTP/3 & DNS Resolution",
      description: "Multiplexing, stream prioritization, DNS lookup pipelines, and TLS handshakes.",
      docsHref: "/docs/networking/networking-overview",
      type: "primary",
      level: "beginner",
      sectionId: "protocols",
      keyConcepts: ["HTTP Status Codes", "DNS Record Types", "TLS 1.3 Handshake"],
    },
    {
      id: "be-dns-records",
      title: "DNS Configuration & Troubleshooting",
      description: "Managing A, AAAA, CNAME, TXT, MX records, and propagation debugging.",
      docsHref: "/docs/networking/dns-guide",
      type: "topic",
      level: "beginner",
      sectionId: "protocols",
      keyConcepts: ["DNS Resolvers", "TTL Caching", "Root Nameservers"],
    },

    // Section 2: Linux
    {
      id: "be-linux-admin",
      title: "Linux Server Administration",
      description: "File permissions (chmod, chown), process management, SSH security, and systemd.",
      docsHref: "/docs/linux/linux-overview",
      type: "primary",
      level: "beginner",
      sectionId: "linux",
      keyConcepts: ["systemctl & journalctl", "User & Group Permissions", "Process Inspection (top/htop)"],
    },
    {
      id: "be-linux-processes",
      title: "Linux Processes & Resource Control",
      description: "Background daemons, signals (SIGTERM, SIGKILL), and memory/swap management.",
      docsHref: "/docs/linux/processes",
      type: "primary",
      level: "intermediate",
      sectionId: "linux",
      keyConcepts: ["Process IDs (PID)", "Fork & Exec", "Resource Limits"],
    },

    // Section 3: Language & Runtime
    {
      id: "be-nodejs-core",
      title: "Node.js & Asynchronous Event Loop",
      description: "Non-blocking I/O, Worker Threads, Buffers, Streams, and module resolution.",
      docsHref: "/docs/nodejs/nodejs-overview",
      type: "primary",
      level: "intermediate",
      sectionId: "language",
      badge: "Recommended",
      keyConcepts: ["Event Loop Phases", "Streams & Backpressure", "Error Propagation"],
    },
    {
      id: "be-express-fastify",
      title: "Express.js & API Middleware",
      description: "Routing, request validation, custom error handlers, and middleware pipelines.",
      docsHref: "/docs/express/express-overview",
      type: "primary",
      level: "intermediate",
      sectionId: "language",
      keyConcepts: ["Middleware Chaining", "JSON Body Parsing", "Route Controllers"],
    },

    // Section 4: API Design
    {
      id: "be-rest-architecture",
      title: "RESTful API Standards & Idempotency",
      description: "Resource naming, status codes, cursor pagination, and idempotency headers.",
      docsHref: "/docs/backend/client-server-architecture",
      type: "primary",
      level: "intermediate",
      sectionId: "api-design",
      keyConcepts: ["Statelessness", "Idempotency Keys", "Content Negotiation"],
    },
    {
      id: "be-cors-security",
      title: "CORS & Request Security",
      description: "Preflight OPTIONS requests, allowed origins, and security headers.",
      docsHref: "/errors/web/cors-policy",
      type: "topic",
      level: "intermediate",
      sectionId: "api-design",
      keyConcepts: ["Access-Control-Allow-Origin", "Preflight Handling", "Credentials Flag"],
    },

    // Section 5: Databases
    {
      id: "be-postgresql-core",
      title: "PostgreSQL Relational Database",
      description: "Schema design, normalized tables, foreign keys, and ACID transactions.",
      docsHref: "/docs/postgresql/postgresql-overview",
      type: "primary",
      level: "intermediate",
      sectionId: "databases",
      badge: "Must Know",
      keyConcepts: ["Table Constraints", "Foreign Keys", "ACID Guarantees"],
    },
    {
      id: "be-postgresql-indexes",
      title: "SQL Indexing & Query Tuning",
      description: "B-Tree indexes, GIN, composite indexes, and EXPLAIN ANALYZE diagnosis.",
      docsHref: "/docs/postgresql/indexes",
      type: "primary",
      level: "advanced",
      sectionId: "databases",
      keyConcepts: ["EXPLAIN (ANALYZE, BUFFERS)", "B-Tree Lookups", "Seq Scan Prevention"],
    },

    // Section 6: ORMs
    {
      id: "be-prisma-orm",
      title: "Prisma ORM & Schema Migrations",
      description: "Type-safe database queries, relation filters, and automated migration diffs.",
      docsHref: "/docs/prisma/prisma-overview",
      type: "primary",
      level: "intermediate",
      sectionId: "orms",
      keyConcepts: ["schema.prisma", "Prisma Client", "npx prisma migrate"],
    },

    // Section 7: Authentication
    {
      id: "be-auth-authz",
      title: "Authentication vs Authorization (RBAC)",
      description: "JWT verification, refresh token rotation, bcrypt password hashing, and sessions.",
      docsHref: "/docs/backend/auth-vs-authz",
      type: "primary",
      level: "intermediate",
      sectionId: "auth",
      keyConcepts: ["JWT Signatures", "Refresh Token Rotation", "Role-Based Access Control"],
    },
    {
      id: "be-cookies-storage",
      title: "HttpOnly Cookies & Session Stores",
      description: "Secure cookie flags (SameSite, Secure, HttpOnly) and session storage.",
      docsHref: "/docs/backend/cookies",
      type: "topic",
      level: "intermediate",
      sectionId: "auth",
      keyConcepts: ["HttpOnly Flag", "SameSite Strict vs Lax", "Cookie Expiry"],
    },

    // Section 8: Caching
    {
      id: "be-redis-caching",
      title: "Redis In-Memory Caching & Sessions",
      description: "Cache-Aside pattern, TTL expiration policies, rate limiting, and pub/sub.",
      docsHref: "/docs/backend/cookies",
      type: "primary",
      level: "advanced",
      sectionId: "caching",
      keyConcepts: ["Cache-Aside Pattern", "TTL Expiration", "Token Bucket Rate Limiter"],
    },

    // Section 9: Containers & Deployment
    {
      id: "be-docker-containers",
      title: "Docker Containerization",
      description: "Multi-stage Dockerfiles, Alpine images, Compose files, and volume persistence.",
      docsHref: "/commands/docker/run",
      type: "primary",
      level: "intermediate",
      sectionId: "containers",
      keyConcepts: ["Multi-Stage Builds", "Docker Compose", "Port Mapping"],
    },
    {
      id: "be-nginx-proxy",
      title: "Nginx Reverse Proxy & SSL",
      description: "Upstream load balancing, SSL/TLS termination, and gzip compression.",
      docsHref: "/recipes/devops/nginx-reverse-proxy-ssl",
      type: "primary",
      level: "advanced",
      sectionId: "containers",
      keyConcepts: ["proxy_pass", "Certbot SSL Automation", "Upstream Round-Robin"],
    },

    // Section 10: Production
    {
      id: "be-system-design",
      title: "System Design & Horizontal Scaling",
      description: "Stateless microservices, database read replicas, connection pooling, and failovers.",
      docsHref: "/docs/backend/client-server-architecture",
      type: "advanced",
      level: "advanced",
      sectionId: "production",
      keyConcepts: ["Horizontal Scaling", "Database Replication", "Circuit Breakers"],
    },
  ],
  edges: [
    { source: "be-http-dns", target: "be-dns-records", type: "primary" },
    { source: "be-dns-records", target: "be-linux-admin", type: "primary" },
    { source: "be-linux-admin", target: "be-linux-processes", type: "primary" },
    { source: "be-linux-processes", target: "be-nodejs-core", type: "primary" },
    { source: "be-nodejs-core", target: "be-express-fastify", type: "primary" },
    { source: "be-express-fastify", target: "be-rest-architecture", type: "primary" },
    { source: "be-rest-architecture", target: "be-cors-security", type: "primary" },
    { source: "be-cors-security", target: "be-postgresql-core", type: "primary" },
    { source: "be-postgresql-core", target: "be-postgresql-indexes", type: "primary" },
    { source: "be-postgresql-indexes", target: "be-prisma-orm", type: "primary" },
    { source: "be-prisma-orm", target: "be-auth-authz", type: "primary" },
    { source: "be-auth-authz", target: "be-cookies-storage", type: "primary" },
    { source: "be-cookies-storage", target: "be-redis-caching", type: "primary" },
    { source: "be-redis-caching", target: "be-docker-containers", type: "primary" },
    { source: "be-docker-containers", target: "be-nginx-proxy", type: "primary" },
    { source: "be-nginx-proxy", target: "be-system-design", type: "primary" },
  ],
};
