import type { RoadmapDefinition } from "../types";

export const devopsRoadmap: RoadmapDefinition = {
  slug: "devops",
  title: "DevOps & Cloud Engineer Roadmap",
  subtitle: "Step-by-step path from Linux systems to Kubernetes, CI/CD, Terraform, and Cloud Reliability",
  description:
    "Master operating systems, cloud networking, Docker containerization, automated GitHub Actions pipelines, Kubernetes cluster orchestration, and Infrastructure as Code.",
  category: "role",
  featured: true,
  icon: "cloud",
  level: "Intermediate → Production",
  estimatedDuration: "10 - 14 Months",
  relatedRoadmaps: ["linux", "docker", "networking", "kubernetes", "backend", "full-stack"],
  sections: [
    { id: "linux-os", title: "1. Operating Systems & Linux Internals", order: 1 },
    { id: "networking", title: "2. Cloud Networking & Security", order: 2 },
    { id: "containers", title: "3. Containers & Image Optimization", order: 3 },
    { id: "cicd", title: "4. CI/CD & Pipeline Automation", order: 4 },
    { id: "orchestration", title: "5. Kubernetes Container Orchestration", order: 5 },
    { id: "iac", title: "6. Infrastructure as Code (Terraform)", order: 6 },
    { id: "observability", title: "7. Observability & Log Aggregation", order: 7 },
  ],
  nodes: [
    // Section 1: Linux
    {
      id: "do-linux-internals",
      title: "Linux Filesystem & Permissions",
      description: "Root filesystems, mount points, ACLs, SUID/SGID, and user group management.",
      docsHref: "/docs/linux/filesystem-hierarchy",
      type: "primary",
      level: "beginner",
      sectionId: "linux-os",
      keyConcepts: ["Filesystem Hierarchy Standard", "chmod & chown", "Access Control Lists"],
    },
    {
      id: "do-linux-systemd",
      title: "Systemd Services & Daemons",
      description: "Writing unit files, managing background services, restart policies, and journalctl.",
      docsHref: "/docs/linux/systemd",
      type: "primary",
      level: "intermediate",
      sectionId: "linux-os",
      keyConcepts: ["Service Unit Structure", "journalctl Log Inspection", "systemctl status/enable"],
    },
    {
      id: "do-disk-inspection",
      title: "Disk & Inode Saturation Cleanup",
      description: "Inspecting df, du, finding bloated log files, and fixing disk full alerts.",
      docsHref: "/commands/linux/disk-usage",
      type: "topic",
      level: "beginner",
      sectionId: "linux-os",
      keyConcepts: ["df -h & du -sh", "Inode Exhaustion", "Logrotate Configuration"],
    },

    // Section 2: Networking
    {
      id: "do-devops-networking",
      title: "DevOps Networking & CIDR Subnetting",
      description: "IP routing, VPC subnet calculations, NAT gateways, and firewall rules.",
      docsHref: "/docs/devops-networking/devops-networking-overview",
      type: "primary",
      level: "intermediate",
      sectionId: "networking",
      keyConcepts: ["CIDR Block Notation", "Public vs Private Subnets", "iptables & nftables"],
    },
    {
      id: "do-ssl-certs",
      title: "SSL/TLS & Certificate Automation",
      description: "Let's Encrypt Certbot ACME automation and Cloudflare Origin SSL configuration.",
      docsHref: "/recipes/devops/cloudflare-origin-ssl-setup",
      type: "primary",
      level: "intermediate",
      sectionId: "networking",
      keyConcepts: ["ACME Challenge", "Full (Strict) SSL", "TLS 1.3 Ciphers"],
    },

    // Section 3: Containers
    {
      id: "do-docker-core",
      title: "Docker Multi-Stage Container Builds",
      description: "Layer caching, non-root users, Alpine images, and container lifecycles.",
      docsHref: "/docs/docker/multi-stage-builds",
      type: "primary",
      level: "intermediate",
      sectionId: "containers",
      keyConcepts: ["Builder Stage Pattern", "Layer Cache Optimization", "Rootless Containers"],
    },
    {
      id: "do-docker-networks",
      title: "Docker Compose & Bridge Networks",
      description: "Local microservice orchestration, port mapping, and DNS service discovery.",
      docsHref: "/docs/docker/networks",
      type: "primary",
      level: "intermediate",
      sectionId: "containers",
      keyConcepts: ["Bridge vs Host Network", "Docker DNS Resolution", "Volume Persistence"],
    },
    {
      id: "do-docker-prune",
      title: "Docker System Prune & Image Cleanup",
      description: "Reclaiming gigabytes of unused images, dangling build caches, and volumes.",
      docsHref: "/commands/docker/system-prune",
      type: "topic",
      level: "intermediate",
      sectionId: "containers",
      keyConcepts: ["docker system prune -a", "Dangling Layers", "BuildKit Cache"],
    },

    // Section 4: CI/CD
    {
      id: "do-gha-workflows",
      title: "GitHub Actions CI/CD Pipelines",
      description: "Automated linting, matrix testing, Docker image building, and deployment triggers.",
      docsHref: "/docs/github-actions/github-actions-overview",
      type: "primary",
      level: "intermediate",
      sectionId: "cicd",
      keyConcepts: ["DAG Workflow Syntax", "Action Caches", "Secrets Masking"],
    },
    {
      id: "do-gha-runners",
      title: "Runners, Environments & OIDC Cloud Auth",
      description: "Self-hosted runners, concurrency gates, deployment approvals, and passwordless OIDC.",
      docsHref: "/docs/github-actions/github-actions-jobs-runners",
      type: "primary",
      level: "advanced",
      sectionId: "cicd",
      keyConcepts: ["Self-Hosted Runners", "OIDC AWS/GCP Authentication", "Environment Protection"],
    },

    // Section 5: Kubernetes
    {
      id: "do-k8s-core",
      title: "Kubernetes Cluster Architecture",
      description: "Control plane components (API server, etcd, scheduler) and node worker agents.",
      docsHref: "/docs/kubernetes/kubernetes-overview",
      type: "primary",
      level: "advanced",
      sectionId: "orchestration",
      keyConcepts: ["kube-apiserver & etcd", "Kubelet & kube-proxy", "Declarative Reconciliation"],
    },
    {
      id: "do-k8s-workloads",
      title: "Pods, Deployments & Ingress Routing",
      description: "ReplicaSets, zero-downtime rolling updates, Ingress controllers, and HPA.",
      docsHref: "/docs/kubernetes/kubernetes-overview",
      type: "primary",
      level: "advanced",
      sectionId: "orchestration",
      keyConcepts: ["RollingUpdate Strategy", "Horizontal Pod Autoscaler (HPA)", "Ingress TLS"],
    },

    // Section 6: IaC
    {
      id: "do-terraform-iac",
      title: "Terraform Infrastructure as Code",
      description: "Declarative HCL syntax, state locking in S3/DynamoDB, modules, and plan vs apply.",
      docsHref: "/recipes/devops/cloudflare-origin-ssl-setup",
      type: "primary",
      level: "advanced",
      sectionId: "iac",
      keyConcepts: ["Remote State Locking", "Terraform Modules", "Execution Plan Auditing"],
    },

    // Section 7: Observability
    {
      id: "do-observability-stack",
      title: "Monitoring, Metrics & Log Aggregation",
      description: "Prometheus scraping, PromQL alert rules, Grafana dashboards, and Loki logs.",
      docsHref: "/docs/linux/linux-overview",
      type: "primary",
      level: "advanced",
      sectionId: "observability",
      keyConcepts: ["PromQL Queries", "SLOs & SLIs", "Distributed Tracing"],
    },
  ],
  edges: [
    { source: "do-linux-internals", target: "do-linux-systemd", type: "primary" },
    { source: "do-linux-systemd", target: "do-disk-inspection", type: "primary" },
    { source: "do-disk-inspection", target: "do-devops-networking", type: "primary" },
    { source: "do-devops-networking", target: "do-ssl-certs", type: "primary" },
    { source: "do-ssl-certs", target: "do-docker-core", type: "primary" },
    { source: "do-docker-core", target: "do-docker-networks", type: "primary" },
    { source: "do-docker-networks", target: "do-docker-prune", type: "primary" },
    { source: "do-docker-prune", target: "do-gha-workflows", type: "primary" },
    { source: "do-gha-workflows", target: "do-gha-runners", type: "primary" },
    { source: "do-gha-runners", target: "do-k8s-core", type: "primary" },
    { source: "do-k8s-core", target: "do-k8s-workloads", type: "primary" },
    { source: "do-k8s-workloads", target: "do-terraform-iac", type: "primary" },
    { source: "do-terraform-iac", target: "do-observability-stack", type: "primary" },
  ],
};
