import type { RoadmapDefinition } from "../types";

export const dockerRoadmap: RoadmapDefinition = {
  slug: "docker",
  title: "Docker & Containerization Roadmap",
  subtitle: "Master Images, Multi-Stage Builds, Volumes, Networks, Compose, and Production Security",
  description:
    "Comprehensive guide from basic container lifecycles to multi-stage Dockerfiles, Docker Compose, networking bridges, and production hardening.",
  category: "devops",
  featured: false,
  icon: "cloud",
  level: "Beginner → Advanced",
  estimatedDuration: "2 - 3 Months",
  relatedRoadmaps: ["devops", "kubernetes", "backend", "linux"],
  sections: [
    { id: "concepts", title: "1. Container Concepts & CLI Basics", order: 1 },
    { id: "images", title: "2. Images & Multi-Stage Dockerfiles", order: 2 },
    { id: "storage-net", title: "3. Volumes & Container Networks", order: 3 },
    { id: "compose", title: "4. Docker Compose & Multi-Container", order: 4 },
    { id: "production", title: "5. Production Best Practices & Security", order: 5 },
  ],
  nodes: [
    {
      id: "docker-containers-core",
      title: "Containers vs Virtual Machines",
      description: "Namespace isolation, cgroups, process lifecycles, and container runtimes.",
      docsHref: "/docs/docker/containers",
      type: "primary",
      level: "beginner",
      sectionId: "concepts",
      keyConcepts: ["Linux Namespaces", "cgroups Memory/CPU", "PID 1 Lifecycle"],
    },
    {
      id: "docker-cli-run",
      title: "Docker Run & Lifecycle Commands",
      description: "Port publishing (-p), environment flags (-e), detach (-d), and restart policies.",
      docsHref: "/commands/docker/run",
      type: "primary",
      level: "beginner",
      sectionId: "concepts",
      keyConcepts: ["docker run -d -p", "docker ps & logs", "Restart Policies"],
    },
    {
      id: "docker-dockerfile",
      title: "Dockerfile Instructions & Caching",
      description: "FROM, WORKDIR, COPY, RUN, EXPOSE, CMD vs ENTRYPOINT, and layer ordering.",
      docsHref: "/docs/docker/dockerfile",
      type: "primary",
      level: "beginner",
      sectionId: "images",
      keyConcepts: ["Layer Cache Optimization", "CMD vs ENTRYPOINT", "Non-Root USER"],
    },
    {
      id: "docker-multistage",
      title: "Multi-Stage Docker Builds",
      description: "Separating build dependencies from runtime for lean production images under 50MB.",
      docsHref: "/docs/docker/multi-stage-builds",
      type: "primary",
      level: "intermediate",
      sectionId: "images",
      keyConcepts: ["Builder Pattern", "Alpine Base Images", "Static Binary Copy"],
    },
    {
      id: "docker-volumes-storage",
      title: "Volumes & Named Storage",
      description: "Persistent data storage, bind mounts for hot-reloading, and anonymous volumes.",
      docsHref: "/docs/docker/volumes",
      type: "primary",
      level: "intermediate",
      sectionId: "storage-net",
      keyConcepts: ["Named Volumes", "Bind Mounts", "Permissions Alignment"],
    },
    {
      id: "docker-networks-bridge",
      title: "Container Networks & DNS Discovery",
      description: "Bridge networks, host networking, and automatic container name resolution.",
      docsHref: "/docs/docker/networks",
      type: "primary",
      level: "intermediate",
      sectionId: "storage-net",
      keyConcepts: ["Custom Bridge Network", "Docker DNS", "Host vs Bridge Mode"],
    },
    {
      id: "docker-compose-stack",
      title: "Docker Compose Microservices",
      description: "Orchestrating web apps, databases, Redis, and health checks with docker-compose.yml.",
      docsHref: "/docs/docker/docker-compose",
      type: "primary",
      level: "intermediate",
      sectionId: "compose",
      keyConcepts: ["docker compose up -d", "depends_on & healthcheck", "Environment Files (.env)"],
    },
    {
      id: "docker-prod-security",
      title: "Production Best Practices & Security",
      description: "Running as non-root, read-only root filesystems, dropping Linux capabilities, and scanning.",
      docsHref: "/docs/docker/production-best-practices",
      type: "primary",
      level: "advanced",
      sectionId: "production",
      keyConcepts: ["USER node / non-root", "docker scan / Trivy", "Health Checks"],
    },
  ],
  edges: [
    { source: "docker-containers-core", target: "docker-cli-run", type: "primary" },
    { source: "docker-cli-run", target: "docker-dockerfile", type: "primary" },
    { source: "docker-dockerfile", target: "docker-multistage", type: "primary" },
    { source: "docker-multistage", target: "docker-volumes-storage", type: "primary" },
    { source: "docker-volumes-storage", target: "docker-networks-bridge", type: "primary" },
    { source: "docker-networks-bridge", target: "docker-compose-stack", type: "primary" },
    { source: "docker-compose-stack", target: "docker-prod-security", type: "primary" },
  ],
};
