import type { RoadmapDefinition } from "../types";

export const frontendRoadmap: RoadmapDefinition = {
  slug: "frontend",
  title: "Frontend Developer Roadmap",
  subtitle: "Step-by-step path to becoming a production-grade Frontend Engineer in 2026",
  description:
    "Master web standards, modern CSS, JavaScript (ES6+), TypeScript, React 19, Next.js App Router, testing, and Core Web Vitals optimization.",
  category: "role",
  featured: true,
  icon: "code",
  level: "Beginner → Production",
  estimatedDuration: "6 - 9 Months",
  relatedRoadmaps: ["javascript", "typescript", "react", "nextjs", "angular", "full-stack"],
  sections: [
    { id: "internet", title: "1. Internet & Browser Fundamentals", order: 1 },
    { id: "html", title: "2. HTML5 & Semantic Web", order: 2 },
    { id: "css", title: "3. Modern CSS & Styling", order: 3 },
    { id: "javascript", title: "4. JavaScript (ES6+) Core", order: 4 },
    { id: "vcs", title: "5. Version Control & Package Managers", order: 5 },
    { id: "typescript", title: "6. TypeScript & Static Typing", order: 6 },
    { id: "frameworks", title: "7. Frontend UI Frameworks", order: 7 },
    { id: "react-nextjs", title: "8. Full-Stack React & Next.js", order: 8 },
    { id: "testing", title: "9. Testing & Quality Assurance", order: 9 },
    { id: "performance", title: "10. Web Performance & Deployment", order: 10 },
  ],
  nodes: [
    // Section 1: Internet
    {
      id: "fe-how-internet-works",
      title: "How the Internet Works",
      description: "Packets, IP addresses, routers, TCP/IP stack, and client-server communication.",
      docsHref: "/docs/networking/networking-overview",
      type: "primary",
      level: "beginner",
      sectionId: "internet",
      keyConcepts: ["TCP/IP Model", "Packet Routing", "IP Addressing"],
    },
    {
      id: "fe-http-https",
      title: "HTTP / HTTPS & DNS",
      description: "Request-response cycles, status codes, headers, SSL/TLS, and DNS lookup.",
      docsHref: "/docs/networking/dns-guide",
      type: "primary",
      level: "beginner",
      sectionId: "internet",
      keyConcepts: ["HTTP Verbs (GET/POST/PUT/DELETE)", "Status Codes", "A & CNAME Records"],
    },
    {
      id: "fe-browser-rendering",
      title: "Browser Rendering Pipeline",
      description: "Critical rendering path: DOM tree, CSSOM, layout, paint, and composite steps.",
      docsHref: "/docs/html/index",
      type: "topic",
      level: "beginner",
      sectionId: "internet",
      keyConcepts: ["DOM & CSSOM", "Reflows & Repaints", "Render Tree"],
    },

    // Section 2: HTML
    {
      id: "fe-html-semantics",
      title: "Semantic HTML Elements",
      description: "Structure accessible documents using <main>, <article>, <nav>, and <section>.",
      docsHref: "/docs/html/semantic-elements",
      type: "primary",
      level: "beginner",
      sectionId: "html",
      keyConcepts: ["Heading Hierarchy", "ARIA Roles", "Landmark Elements"],
    },
    {
      id: "fe-html-forms",
      title: "HTML5 Forms & Validations",
      description: "Accessible form controls, required validations, input types, and form submission.",
      docsHref: "/docs/html/index",
      type: "topic",
      level: "beginner",
      sectionId: "html",
      keyConcepts: ["Input Attributes", "Form Validation API", "Accessibility (a11y)"],
    },

    // Section 3: CSS
    {
      id: "fe-css-box-model",
      title: "CSS Fundamentals & Box Model",
      description: "Content, padding, border, margin, box-sizing, and specificity rules.",
      docsHref: "/docs/css/box-model",
      type: "primary",
      level: "beginner",
      sectionId: "css",
      keyConcepts: ["box-sizing: border-box", "Margin Collapsing", "Specificity Calculation"],
    },
    {
      id: "fe-css-flexbox-grid",
      title: "Flexbox & CSS Grid",
      description: "Two-dimensional responsive layouts, alignments, auto-fill, and template areas.",
      docsHref: "/docs/css/layout-cheatsheet",
      type: "primary",
      level: "beginner",
      sectionId: "css",
      keyConcepts: ["Flex Direction & Justify", "Grid Template Areas", "fr Units & minmax()"],
    },
    {
      id: "fe-tailwind-css",
      title: "Tailwind CSS",
      description: "Utility-first CSS styling, arbitrary variants, and design token integration.",
      docsHref: "/docs/tailwindcss/tailwindcss-overview",
      type: "primary",
      level: "intermediate",
      sectionId: "css",
      keyConcepts: ["JIT Compiler", "Responsive Prefixes", "Theme Configuration"],
    },

    // Section 4: JavaScript
    {
      id: "fe-js-fundamentals",
      title: "JavaScript Variables & Scope",
      description: "let/const vs var, lexical scope, closures, and primitive vs reference types.",
      docsHref: "/docs/javascript/variables",
      type: "primary",
      level: "beginner",
      sectionId: "javascript",
      keyConcepts: ["Block Scope", "Hoisting", "Closures"],
    },
    {
      id: "fe-js-functions",
      title: "Functions & Array Methods",
      description: "Arrow functions, map, filter, reduce, destructuring, and rest/spread.",
      docsHref: "/docs/javascript/functions",
      type: "primary",
      level: "beginner",
      sectionId: "javascript",
      keyConcepts: ["Higher-Order Functions", "Pure Functions", "Array Transformations"],
    },
    {
      id: "fe-js-dom",
      title: "DOM Manipulation & Events",
      description: "Query selectors, event listeners, bubbling, delegation, and dynamic rendering.",
      docsHref: "/docs/javascript/dom-basics",
      type: "primary",
      level: "beginner",
      sectionId: "javascript",
      keyConcepts: ["addEventListener", "Event Delegation", "Event.stopPropagation()"],
    },
    {
      id: "fe-js-async",
      title: "Promises, Async/Await & Event Loop",
      description: "Microtasks vs macrotasks, fetch API, error handling, and parallel execution.",
      docsHref: "/docs/javascript/async-await",
      type: "primary",
      level: "intermediate",
      sectionId: "javascript",
      keyConcepts: ["Call Stack", "Microtask Queue", "Promise.all() & allSettled()"],
    },

    // Section 5: VCS & Tools
    {
      id: "fe-git",
      title: "Git & GitHub Collaboration",
      description: "Branching, staging, committing, interactive rebasing, and pull requests.",
      docsHref: "/docs/git/git-overview",
      type: "primary",
      level: "beginner",
      sectionId: "vcs",
      keyConcepts: ["git rebase -i", "Resolving Conflicts", "PR Reviews"],
    },
    {
      id: "fe-package-managers",
      title: "pnpm & npm Package Managers",
      description: "Fast dependency management, lockfiles, semver, and workspace monorepos.",
      docsHref: "/docs/package-managers/package-managers-overview",
      type: "topic",
      level: "beginner",
      sectionId: "vcs",
      keyConcepts: ["pnpm Hard Links", "package-lock.json", "Node Modules Isolation"],
    },

    // Section 6: TypeScript
    {
      id: "fe-typescript-core",
      title: "TypeScript Static Typing",
      description: "Interfaces, Generics, Utility types, Discriminated Unions, and Strict Mode.",
      docsHref: "/docs/typescript/typescript-overview",
      type: "primary",
      level: "intermediate",
      sectionId: "typescript",
      keyConcepts: ["Generics <T>", "Discriminated Unions", "Partial<T> & Omit<T>"],
    },

    // Section 7: Frameworks
    {
      id: "fe-framework-react",
      title: "React (v19) - Industry Standard",
      description: "Component lifecycle, state, hooks, custom hooks, Suspense, and Actions.",
      docsHref: "/docs/react/react-overview",
      type: "primary",
      level: "intermediate",
      sectionId: "frameworks",
      badge: "Recommended",
      keyConcepts: ["useState & useEffect", "Custom Hooks", "React 19 Actions"],
    },
    {
      id: "fe-framework-angular",
      title: "Angular - Enterprise Choice",
      description: "Standalone components, Signals, Dependency Injection, and typed forms.",
      docsHref: "/docs/angular/angular-overview",
      type: "alternative",
      level: "intermediate",
      sectionId: "frameworks",
      badge: "Alternative",
      keyConcepts: ["Signals & Computed", "Standalone Components", "Dependency Injection"],
    },

    // Section 8: Full-Stack React & Next.js
    {
      id: "fe-nextjs-app-router",
      title: "Next.js 15+ App Router",
      description: "React Server Components (RSC), Server Actions, nested layouts, and SSR/SSG.",
      docsHref: "/docs/nextjs/nextjs-overview",
      type: "primary",
      level: "advanced",
      sectionId: "react-nextjs",
      keyConcepts: ["Server Components (RSC)", "Server Actions", "Route Handlers"],
    },
    {
      id: "fe-nextjs-caching",
      title: "Data Fetching & Cache Revalidation",
      description: "Incremental Static Regeneration (ISR), tag-based revalidation, and caching layers.",
      docsHref: "/docs/nextjs/caching-concepts",
      type: "advanced",
      level: "advanced",
      sectionId: "react-nextjs",
      keyConcepts: ["revalidatePath()", "unstable_cache", "Stale While Revalidate"],
    },

    // Section 9: Testing
    {
      id: "fe-testing-qa",
      title: "Component & E2E Testing",
      description: "Unit testing pure utilities, React Testing Library user flows, and Playwright.",
      docsHref: "/docs/react/common-react-mistakes",
      type: "topic",
      level: "intermediate",
      sectionId: "testing",
      keyConcepts: ["Unit Tests", "Component Integration", "Regression Prevention"],
    },

    // Section 10: Performance & Deployment
    {
      id: "fe-core-web-vitals",
      title: "Core Web Vitals & Performance",
      description: "LCP, INP, CLS optimization, dynamic code-splitting, and font/image loading.",
      docsHref: "/docs/nextjs/performance",
      type: "primary",
      level: "advanced",
      sectionId: "performance",
      keyConcepts: ["Largest Contentful Paint (LCP)", "Interaction to Next Paint (INP)", "Dynamic Imports"],
    },
    {
      id: "fe-deployment-edge",
      title: "Production Deployment & CDN",
      description: "Vercel, Cloudflare Pages, Edge network distribution, and HTTPS SSL certificates.",
      docsHref: "/docs/nextjs/deployment",
      type: "primary",
      level: "advanced",
      sectionId: "performance",
      keyConcepts: ["Edge CDN Delivery", "Environment Secrets", "Custom Domains & DNS"],
    },
  ],
  edges: [
    { source: "fe-how-internet-works", target: "fe-http-https", type: "primary" },
    { source: "fe-http-https", target: "fe-browser-rendering", type: "primary" },
    { source: "fe-browser-rendering", target: "fe-html-semantics", type: "primary" },
    { source: "fe-html-semantics", target: "fe-html-forms", type: "primary" },
    { source: "fe-html-forms", target: "fe-css-box-model", type: "primary" },
    { source: "fe-css-box-model", target: "fe-css-flexbox-grid", type: "primary" },
    { source: "fe-css-flexbox-grid", target: "fe-tailwind-css", type: "primary" },
    { source: "fe-tailwind-css", target: "fe-js-fundamentals", type: "primary" },
    { source: "fe-js-fundamentals", target: "fe-js-functions", type: "primary" },
    { source: "fe-js-functions", target: "fe-js-dom", type: "primary" },
    { source: "fe-js-dom", target: "fe-js-async", type: "primary" },
    { source: "fe-js-async", target: "fe-git", type: "primary" },
    { source: "fe-git", target: "fe-package-managers", type: "primary" },
    { source: "fe-package-managers", target: "fe-typescript-core", type: "primary" },
    { source: "fe-typescript-core", target: "fe-framework-react", type: "primary" },
    { source: "fe-typescript-core", target: "fe-framework-angular", type: "alternative" },
    { source: "fe-framework-react", target: "fe-nextjs-app-router", type: "primary" },
    { source: "fe-nextjs-app-router", target: "fe-nextjs-caching", type: "primary" },
    { source: "fe-nextjs-caching", target: "fe-testing-qa", type: "primary" },
    { source: "fe-testing-qa", target: "fe-core-web-vitals", type: "primary" },
    { source: "fe-core-web-vitals", target: "fe-deployment-edge", type: "primary" },
  ],
};
