import type { RoadmapDefinition } from "../types";

export const fullStackRoadmap: RoadmapDefinition = {
  slug: "full-stack",
  title: "Full Stack Developer Roadmap",
  subtitle: "Master the complete web engineering spectrum from browser interfaces to production databases",
  description:
    "Bridge modern React/Next.js frontends, Node.js REST APIs, PostgreSQL relational data modeling, containerized deployments, and edge delivery.",
  category: "role",
  featured: true,
  icon: "layers",
  level: "Intermediate → Production",
  estimatedDuration: "10 - 14 Months",
  relatedRoadmaps: ["frontend", "backend", "react", "nextjs", "nodejs", "postgresql", "docker"],
  sections: [
    { id: "fe-stack", title: "1. Modern Frontend & Client Architecture", order: 1 },
    { id: "be-stack", title: "2. Backend APIs & Microservices", order: 2 },
    { id: "db-stack", title: "3. Database Design & ORM Integration", order: 3 },
    { id: "auth-stack", title: "4. Full-Stack Authentication & Security", order: 4 },
    { id: "deploy-stack", title: "5. Containerization, CI/CD & Cloud", order: 5 },
  ],
  nodes: [
    {
      id: "fs-react-nextjs",
      title: "React 19 & Next.js App Router",
      description: "Server Components, Server Actions, routing, and Tailwind CSS responsive design.",
      docsHref: "/docs/nextjs/nextjs-overview",
      type: "primary",
      level: "intermediate",
      sectionId: "fe-stack",
      keyConcepts: ["React Server Components", "Server Actions", "Streaming Suspense"],
    },
    {
      id: "fs-typescript-e2e",
      title: "End-to-End TypeScript",
      description: "Shared schema validation with Zod, strict type inference, and API contracts.",
      docsHref: "/docs/typescript/typescript-overview",
      type: "primary",
      level: "intermediate",
      sectionId: "fe-stack",
      keyConcepts: ["Type-Safe Contracts", "Zod Validation", "Generics"],
    },
    {
      id: "fs-nodejs-express",
      title: "Node.js & Express REST APIs",
      description: "Non-blocking event loop, middleware pipelines, error handlers, and route controllers.",
      docsHref: "/docs/nodejs/nodejs-overview",
      type: "primary",
      level: "intermediate",
      sectionId: "be-stack",
      keyConcepts: ["REST Standards", "Middleware Chaining", "JSON Serialization"],
    },
    {
      id: "fs-postgresql-prisma",
      title: "PostgreSQL & Prisma ORM",
      description: "Relational data modeling, table constraints, automated migrations, and queries.",
      docsHref: "/docs/postgresql/postgresql-overview",
      type: "primary",
      level: "intermediate",
      sectionId: "db-stack",
      keyConcepts: ["Relational Foreign Keys", "Prisma Client", "Database Migrations"],
    },
    {
      id: "fs-auth-sessions",
      title: "JWT & Session Authentication",
      description: "HttpOnly cookie tokens, refresh token rotation, bcrypt hashing, and protected routes.",
      docsHref: "/recipes/auth/react-nextjs-auth-jwt",
      type: "primary",
      level: "intermediate",
      sectionId: "auth-stack",
      keyConcepts: ["HttpOnly Cookies", "JWT Signatures", "Role-Based Permissions"],
    },
    {
      id: "fs-docker-deploy",
      title: "Docker Containerization & Deployment",
      description: "Containerizing full-stack apps with Docker Compose and deploying behind Nginx.",
      docsHref: "/commands/docker/run",
      type: "primary",
      level: "advanced",
      sectionId: "deploy-stack",
      keyConcepts: ["Docker Compose", "Multi-Stage Dockerfile", "Nginx Reverse Proxy"],
    },
  ],
  edges: [
    { source: "fs-react-nextjs", target: "fs-typescript-e2e", type: "primary" },
    { source: "fs-typescript-e2e", target: "fs-nodejs-express", type: "primary" },
    { source: "fs-nodejs-express", target: "fs-postgresql-prisma", type: "primary" },
    { source: "fs-postgresql-prisma", target: "fs-auth-sessions", type: "primary" },
    { source: "fs-auth-sessions", target: "fs-docker-deploy", type: "primary" },
  ],
};
