import type { RoadmapDefinition } from "../types";

export const gitRoadmap: RoadmapDefinition = {
  slug: "git",
  title: "Git & GitHub Collaboration Roadmap",
  subtitle: "Master Version Control, Branching Models, Interactive Rebasing, and Conflict Resolution",
  description:
    "Comprehensive guide from basic commits and staging to interactive rebasing, merge conflict resolution, reflog recovery, and trunk-based workflows.",
  category: "tools",
  featured: false,
  icon: "code",
  level: "Beginner → Advanced",
  estimatedDuration: "1 - 2 Months",
  relatedRoadmaps: ["frontend", "backend", "devops", "full-stack"],
  sections: [
    { id: "foundations", title: "1. Staging, Commits & History", order: 1 },
    { id: "branching", title: "2. Branching & Merging", order: 2 },
    { id: "advanced", title: "3. Rebasing, Stashing & History Rewriting", order: 3 },
    { id: "recovery", title: "4. Reflog, Reverting & Disaster Recovery", order: 4 },
  ],
  nodes: [
    {
      id: "git-init-commits",
      title: "Git Initialization & Staging Area",
      description: "Working directory, staging area (index), git add, git commit, and commit messages.",
      docsHref: "/docs/git/git-commit",
      type: "primary",
      level: "beginner",
      sectionId: "foundations",
      keyConcepts: ["Three States (Working/Staging/Committed)", "Atomic Commits", "Conventional Commits"],
    },
    {
      id: "git-branch-merge",
      title: "Branching, Switching & Merging",
      description: "Fast-forward merges, three-way merges, git switch, and resolving merge conflicts.",
      docsHref: "/docs/git/branches",
      type: "primary",
      level: "beginner",
      sectionId: "branching",
      keyConcepts: ["git branch & switch", "Fast-Forward vs Merge Commit", "Conflict Markers"],
    },
    {
      id: "git-interactive-rebase",
      title: "Interactive Rebasing (git rebase -i)",
      description: "Squashing commits, rewording, dropping commits, and maintaining a linear commit history.",
      docsHref: "/docs/git/rebase",
      type: "primary",
      level: "intermediate",
      sectionId: "advanced",
      keyConcepts: ["git rebase -i HEAD~N", "pick, squash, reword, drop", "Linear History"],
    },
    {
      id: "git-stash-cherrypick",
      title: "Stashing & Cherry-Picking",
      description: "Temporarily shelving uncommitted changes (git stash) and cherry-picking individual commits.",
      docsHref: "/docs/git/stash",
      type: "topic",
      level: "intermediate",
      sectionId: "advanced",
      keyConcepts: ["git stash push/pop", "git cherry-pick <SHA>", "Stash Workflows"],
    },
    {
      id: "git-reflog-undo",
      title: "Reflog & Undoing Disasters",
      description: "Recovering lost commits, dangling heads, git reset (--soft, --mixed, --hard), and git revert.",
      docsHref: "/docs/git/reflog",
      type: "primary",
      level: "advanced",
      sectionId: "recovery",
      keyConcepts: ["git reflog", "git reset --hard HEAD@{n}", "git revert (Safe Undo)"],
    },
  ],
  edges: [
    { source: "git-init-commits", target: "git-branch-merge", type: "primary" },
    { source: "git-branch-merge", target: "git-interactive-rebase", type: "primary" },
    { source: "git-interactive-rebase", target: "git-stash-cherrypick", type: "primary" },
    { source: "git-stash-cherrypick", target: "git-reflog-undo", type: "primary" },
  ],
};
