import type { RoadmapDefinition } from "../types";

export const javascriptRoadmap: RoadmapDefinition = {
  slug: "javascript",
  title: "JavaScript Language Roadmap",
  subtitle: "Master ES6+, Closures, Prototypes, Asynchronous Event Loop, and DOM Engineering",
  description:
    "Comprehensive guide from JavaScript syntax basics to deep runtime mechanics, Microtasks vs Macrotasks, Promises, Modules, and DOM events.",
  category: "language",
  featured: false,
  icon: "code",
  level: "Beginner → Advanced",
  estimatedDuration: "2 - 4 Months",
  relatedRoadmaps: ["frontend", "typescript", "react", "nodejs"],
  sections: [
    { id: "syntax", title: "1. Syntax, Scope & Closures", order: 1 },
    { id: "data-structures", title: "2. Arrays, Objects & Destructuring", order: 2 },
    { id: "async", title: "3. Asynchronous Execution & Event Loop", order: 3 },
    { id: "dom", title: "4. DOM Manipulation & Web APIs", order: 4 },
  ],
  nodes: [
    {
      id: "js-scope-closures",
      title: "Variables, Scope & Closures",
      description: "Lexical scope chain, closures, hoisting, execution contexts, and memory retention.",
      docsHref: "/docs/javascript/closures",
      type: "primary",
      level: "beginner",
      sectionId: "syntax",
      keyConcepts: ["Lexical Scope", "Closures & Private State", "Hoisting"],
    },
    {
      id: "js-arrays-objects",
      title: "Arrays, Objects & Destructuring",
      description: "Array iteration (map, filter, reduce, flatMap), destructuring, rest/spread operators.",
      docsHref: "/docs/javascript/arrays",
      type: "primary",
      level: "beginner",
      sectionId: "data-structures",
      keyConcepts: ["map(), filter(), reduce()", "Object Destructuring", "Spread & Rest"],
    },
    {
      id: "js-event-loop-async",
      title: "Promises, Async/Await & Event Loop",
      description: "Call Stack, Microtask queue (Promises), Macrotask queue (setTimeout), and non-blocking I/O.",
      docsHref: "/docs/javascript/event-loop",
      type: "primary",
      level: "intermediate",
      sectionId: "async",
      keyConcepts: ["Microtasks vs Macrotasks", "Promise.all() & allSettled()", "Async/Await Try/Catch"],
    },
    {
      id: "js-dom-events",
      title: "DOM Manipulation & Event Bubbling",
      description: "Query selectors, event capturing/bubbling, event delegation, and DOM updates.",
      docsHref: "/docs/javascript/dom-basics",
      type: "primary",
      level: "beginner",
      sectionId: "dom",
      keyConcepts: ["Event Delegation", "Event Bubbling vs Capturing", "Element.classList API"],
    },
    {
      id: "js-fetch-network",
      title: "Fetch API & Error Handling",
      description: "HTTP requests with fetch, AbortController cancellation, response parsing, and error guards.",
      docsHref: "/docs/javascript/fetch",
      type: "primary",
      level: "intermediate",
      sectionId: "dom",
      keyConcepts: ["fetch(url, options)", "AbortController Signal", "Response.json()"],
    },
  ],
  edges: [
    { source: "js-scope-closures", target: "js-arrays-objects", type: "primary" },
    { source: "js-arrays-objects", target: "js-event-loop-async", type: "primary" },
    { source: "js-event-loop-async", target: "js-dom-events", type: "primary" },
    { source: "js-dom-events", target: "js-fetch-network", type: "primary" },
  ],
};
