import type { RoadmapDefinition } from "../types";

export const kubernetesRoadmap: RoadmapDefinition = {
  slug: "kubernetes",
  title: "Kubernetes (K8s) Orchestration Roadmap",
  subtitle: "Master Pods, Deployments, Services, Ingress, Helm, and Cloud Cluster Architecture",
  description:
    "Comprehensive guide from Kubernetes architecture (Control Plane & Worker Nodes) to Deployments, Ingress controllers, Helm charts, and HPA auto-scaling.",
  category: "devops",
  featured: false,
  icon: "cloud",
  level: "Intermediate → Advanced",
  estimatedDuration: "3 - 5 Months",
  relatedRoadmaps: ["devops", "docker", "linux", "networking"],
  sections: [
    { id: "architecture", title: "1. Cluster Architecture & Concepts", order: 1 },
    { id: "workloads", title: "2. Workloads (Pods, Deployments, ReplicaSets)", order: 2 },
    { id: "networking", title: "3. Services & Ingress Controllers", order: 3 },
    { id: "config-storage", title: "4. ConfigMaps, Secrets & Storage", order: 4 },
    { id: "packaging", title: "5. Helm Charts & Production Scaling", order: 5 },
  ],
  nodes: [
    {
      id: "k8s-architecture-core",
      title: "Control Plane & Worker Node Components",
      description: "kube-apiserver, etcd key-value store, kube-scheduler, kube-controller-manager, and kubelet.",
      docsHref: "/docs/kubernetes/kubernetes-overview",
      type: "primary",
      level: "intermediate",
      sectionId: "architecture",
      keyConcepts: ["Control Plane Components", "etcd Consensus", "Kubelet Agent"],
    },
    {
      id: "k8s-pods-deployments",
      title: "Pods, ReplicaSets & Deployments",
      description: "Declarative YAML manifests, rolling update strategies, rollbacks, and replica counts.",
      docsHref: "/docs/kubernetes/kubernetes-overview",
      type: "primary",
      level: "intermediate",
      sectionId: "workloads",
      keyConcepts: ["RollingUpdate Strategy", "ReplicaSet Reconciliation", "Container Spec"],
    },
    {
      id: "k8s-services-ingress",
      title: "ClusterIP, NodePort, LoadBalancer & Ingress",
      description: "Service discovery, internal virtual IPs, NGINX Ingress Controller, and TLS termination.",
      docsHref: "/docs/kubernetes/kubernetes-overview",
      type: "primary",
      level: "intermediate",
      sectionId: "networking",
      keyConcepts: ["ClusterIP vs LoadBalancer", "Ingress Host Rules", "kube-proxy iptables"],
    },
    {
      id: "k8s-config-secrets",
      title: "ConfigMaps, Secrets & PersistentVolumes",
      description: "Decoupling configuration, Base64 secrets, PersistentVolumeClaims (PVC), and storage classes.",
      docsHref: "/docs/kubernetes/kubernetes-overview",
      type: "primary",
      level: "intermediate",
      sectionId: "config-storage",
      keyConcepts: ["ConfigMap as Env/Volume", "K8s Secrets", "PVC & Dynamic Provisioning"],
    },
    {
      id: "k8s-helm-scaling",
      title: "Helm Package Manager & HPA Auto-Scaling",
      description: "Parameterized Helm templates, values.yaml overrides, and Horizontal Pod Autoscalers.",
      docsHref: "/docs/kubernetes/kubernetes-overview",
      type: "primary",
      level: "advanced",
      sectionId: "packaging",
      keyConcepts: ["Helm Chart Templates", "Horizontal Pod Autoscaler (HPA)", "Resource Requests & Limits"],
    },
  ],
  edges: [
    { source: "k8s-architecture-core", target: "k8s-pods-deployments", type: "primary" },
    { source: "k8s-pods-deployments", target: "k8s-services-ingress", type: "primary" },
    { source: "k8s-services-ingress", target: "k8s-config-secrets", type: "primary" },
    { source: "k8s-config-secrets", target: "k8s-helm-scaling", type: "primary" },
  ],
};
