import type { RoadmapDefinition } from "../types";

export const linuxRoadmap: RoadmapDefinition = {
  slug: "linux",
  title: "Linux Administration Roadmap",
  subtitle: "Master Linux Operating Systems, Process Management, Permissions, Systemd, and Shell Automation",
  description:
    "Comprehensive guide from basic CLI navigation and file permissions to background services (systemd), networking tools, and disk diagnostics.",
  category: "devops",
  featured: false,
  icon: "server",
  level: "Beginner → Advanced",
  estimatedDuration: "2 - 4 Months",
  relatedRoadmaps: ["devops", "backend", "docker", "networking"],
  sections: [
    { id: "foundations", title: "1. CLI Navigation & Filesystem", order: 1 },
    { id: "permissions", title: "2. Users, Groups & Permissions", order: 2 },
    { id: "processes", title: "3. Processes & System Monitoring", order: 3 },
    { id: "services", title: "4. Systemd & Service Management", order: 4 },
    { id: "networking", title: "5. Linux Networking & SSH", order: 5 },
  ],
  nodes: [
    {
      id: "linux-filesystem",
      title: "Linux Filesystem Hierarchy (FHS)",
      description: "Understanding /etc, /var, /usr, /bin, /home, and absolute vs relative paths.",
      docsHref: "/docs/linux/filesystem-hierarchy",
      type: "primary",
      level: "beginner",
      sectionId: "foundations",
      keyConcepts: ["Filesystem Standard", "Mount Points", "Path Resolution"],
    },
    {
      id: "linux-permissions-core",
      title: "File Permissions (chmod, chown)",
      description: "Read, write, execute permissions (rwx), octal mode (755, 644), and user ownership.",
      docsHref: "/docs/linux/permissions",
      type: "primary",
      level: "beginner",
      sectionId: "permissions",
      keyConcepts: ["chmod 755 vs 600", "chown user:group", "umask Defaults"],
    },
    {
      id: "linux-processes-mgmt",
      title: "Process Inspection & Management",
      description: "Monitoring ps, top, htop, process trees, and sending signals (SIGTERM, SIGKILL).",
      docsHref: "/docs/linux/processes",
      type: "primary",
      level: "beginner",
      sectionId: "processes",
      keyConcepts: ["ps aux", "kill -15 vs -9", "Background Jobs (&, fg, bg)"],
    },
    {
      id: "linux-disk-memory",
      title: "Disk Usage & Memory Diagnosis",
      description: "Inspecting df, du, free -m, finding large files, and diagnosing memory pressure.",
      docsHref: "/docs/linux/disk-usage",
      type: "primary",
      level: "intermediate",
      sectionId: "processes",
      keyConcepts: ["df -h & du -sh", "Swap Memory", "Inode Exhaustion"],
    },
    {
      id: "linux-systemd-services",
      title: "Systemd Units & Background Services",
      description: "Writing .service unit files, restart policies, and journalctl log inspection.",
      docsHref: "/docs/linux/systemd",
      type: "primary",
      level: "intermediate",
      sectionId: "services",
      keyConcepts: ["systemctl status/start/enable", "journalctl -u -f", "Restart=always"],
    },
    {
      id: "linux-ssh-security",
      title: "SSH Key Hardening & Networking Commands",
      description: "Ed25519 SSH keys, disabling password login, curl, netstat, and ufw firewalls.",
      docsHref: "/docs/linux/ssh",
      type: "primary",
      level: "intermediate",
      sectionId: "networking",
      keyConcepts: ["ssh-keygen -t ed25519", "sshd_config Hardening", "ufw allow 22/tcp"],
    },
  ],
  edges: [
    { source: "linux-filesystem", target: "linux-permissions-core", type: "primary" },
    { source: "linux-permissions-core", target: "linux-processes-mgmt", type: "primary" },
    { source: "linux-processes-mgmt", target: "linux-disk-memory", type: "primary" },
    { source: "linux-disk-memory", target: "linux-systemd-services", type: "primary" },
    { source: "linux-systemd-services", target: "linux-ssh-security", type: "primary" },
  ],
};
