import type { RoadmapDefinition } from "../types";

export const networkingRoadmap: RoadmapDefinition = {
  slug: "networking",
  title: "Networking for Developers Roadmap",
  subtitle: "Master the TCP/IP Stack, HTTP/3, DNS, TLS 1.3, Subnetting, and Cloud Firewalls",
  description:
    "Comprehensive guide from basic packet routing and DNS resolution to SSL/TLS handshakes, CIDR subnet calculations, and reverse proxies.",
  category: "devops",
  featured: false,
  icon: "cloud",
  level: "Beginner → Advanced",
  estimatedDuration: "2 - 3 Months",
  relatedRoadmaps: ["backend", "devops", "linux"],
  sections: [
    { id: "protocols", title: "1. Core Network Protocols", order: 1 },
    { id: "dns", title: "2. DNS Architecture & Records", order: 2 },
    { id: "security", title: "3. SSL/TLS & Cryptography", order: 3 },
    { id: "cloud-net", title: "4. CIDR Subnetting & VPCs", order: 4 },
  ],
  nodes: [
    {
      id: "net-tcp-ip",
      title: "TCP/IP vs UDP & Packets",
      description: "Three-way handshakes, SYN/ACK, packet fragmentation, flow control, and port multiplexing.",
      docsHref: "/docs/networking/networking-overview",
      type: "primary",
      level: "beginner",
      sectionId: "protocols",
      keyConcepts: ["TCP 3-Way Handshake", "UDP Datagrams", "Port Numbers & Sockets"],
    },
    {
      id: "net-http-evolution",
      title: "HTTP/1.1, HTTP/2 & HTTP/3 (QUIC)",
      description: "Head-of-line blocking, binary framing, multiplexing streams, and UDP-based QUIC.",
      docsHref: "/docs/networking/networking-overview",
      type: "primary",
      level: "intermediate",
      sectionId: "protocols",
      keyConcepts: ["HTTP Multiplexing", "QUIC Protocol", "Server Push & Headers"],
    },
    {
      id: "net-dns-system",
      title: "DNS Resolution Pipeline & Records",
      description: "Root nameservers, authoritative DNS, TLDs, A, AAAA, CNAME, TXT, MX, and TTL caching.",
      docsHref: "/docs/networking/dns-guide",
      type: "primary",
      level: "beginner",
      sectionId: "dns",
      keyConcepts: ["Recursive Resolvers", "TTL Propagation", "CNAME vs A Record"],
    },
    {
      id: "net-tls-ssl",
      title: "TLS 1.3 Encryption & Certificates",
      description: "Public/Private key pairs, Certificate Authorities (CA), SNI, and automated Certbot ACME.",
      docsHref: "/recipes/devops/cloudflare-origin-ssl-setup",
      type: "primary",
      level: "intermediate",
      sectionId: "security",
      keyConcepts: ["TLS 1.3 1-RTT Handshake", "ACME Challenge", "SNI (Server Name Indication)"],
    },
    {
      id: "net-cidr-subnets",
      title: "CIDR Subnetting & Cloud VPCs",
      description: "IP address classes, /24 and /16 subnet masks, private IP ranges (RFC 1918), and routing tables.",
      docsHref: "/docs/devops-networking/devops-networking-overview",
      type: "primary",
      level: "advanced",
      sectionId: "cloud-net",
      keyConcepts: ["CIDR Math (/24 = 256 IPs)", "Private Subnets (10.0.0.0/8, 192.168.0.0/16)", "NAT Gateways"],
    },
  ],
  edges: [
    { source: "net-tcp-ip", target: "net-http-evolution", type: "primary" },
    { source: "net-http-evolution", target: "net-dns-system", type: "primary" },
    { source: "net-dns-system", target: "net-tls-ssl", type: "primary" },
    { source: "net-tls-ssl", target: "net-cidr-subnets", type: "primary" },
  ],
};
