import type { RoadmapDefinition } from "../types";

export const nextjsRoadmap: RoadmapDefinition = {
  slug: "nextjs",
  title: "Next.js Developer Roadmap",
  subtitle: "Master React Server Components, App Router, Server Actions, and Production Edge Architecture",
  description:
    "Comprehensive guide to Next.js 15+: layouts, routing, streaming SSR, Server Actions, data caching, authentication, and Vercel deployments.",
  category: "framework",
  featured: false,
  icon: "layers",
  level: "Intermediate → Production",
  estimatedDuration: "2 - 4 Months",
  relatedRoadmaps: ["frontend", "react", "full-stack", "typescript"],
  sections: [
    { id: "app-router", title: "1. App Router & File Hierarchy", order: 1 },
    { id: "rendering", title: "2. Server vs Client Components", order: 2 },
    { id: "mutations", title: "3. Server Actions & Mutations", order: 3 },
    { id: "caching", title: "4. Caching, Revalidation & ISR", order: 4 },
    { id: "production", title: "5. Auth, Security & Production Deployment", order: 5 },
  ],
  nodes: [
    {
      id: "next-app-router",
      title: "App Router & File System Routing",
      description: "Layouts, page templates, loading.tsx, error.tsx, and not-found boundaries.",
      docsHref: "/docs/nextjs/app-router",
      type: "primary",
      level: "intermediate",
      sectionId: "app-router",
      keyConcepts: ["layout.tsx vs page.tsx", "loading.tsx Suspense", "Route Groups (folder)"],
    },
    {
      id: "next-server-components",
      title: "React Server Components (RSC)",
      description: "Zero-bundle-size server components, direct database access, and data streaming.",
      docsHref: "/docs/nextjs/server-components",
      type: "primary",
      level: "intermediate",
      sectionId: "rendering",
      keyConcepts: ["Async Components", "Streaming Suspense", "Server-Only Code"],
    },
    {
      id: "next-client-components",
      title: "Client Components ('use client')",
      description: "Event handlers, browser APIs, React state hooks, and client-server boundaries.",
      docsHref: "/docs/nextjs/client-components",
      type: "primary",
      level: "intermediate",
      sectionId: "rendering",
      keyConcepts: ["'use client' Directive", "Interactivity Boundary", "Props Serialization"],
    },
    {
      id: "next-route-handlers",
      title: "Route Handlers & REST Endpoints",
      description: "Creating custom HTTP GET, POST, PUT, DELETE endpoints in app/api/route.ts.",
      docsHref: "/docs/nextjs/route-handlers",
      type: "topic",
      level: "intermediate",
      sectionId: "mutations",
      keyConcepts: ["NextRequest & NextResponse", "HTTP Cookies & Headers", "Web API Standard"],
    },
    {
      id: "next-server-actions",
      title: "Server Actions & Form Handling",
      description: "Type-safe server mutations directly from forms with progressive enhancement.",
      docsHref: "/docs/nextjs/server-actions",
      type: "primary",
      level: "intermediate",
      sectionId: "mutations",
      keyConcepts: ["'use server' Directive", "useActionState", "revalidatePath()"],
    },
    {
      id: "next-caching",
      title: "Caching Architecture & Revalidation",
      description: "Request memoization, Data Cache, Full Route Cache, and Router Cache.",
      docsHref: "/docs/nextjs/caching-concepts",
      type: "primary",
      level: "advanced",
      sectionId: "caching",
      keyConcepts: ["revalidateTag()", "unstable_cache", "Incremental Static Regeneration"],
    },
    {
      id: "next-auth",
      title: "Authentication Architecture & Middleware",
      description: "Securing routes with middleware.ts, session cookies, and JWT verification.",
      docsHref: "/docs/nextjs/authentication-architecture",
      type: "primary",
      level: "advanced",
      sectionId: "production",
      keyConcepts: ["Next.js Middleware", "Session Verification", "Protected Redirects"],
    },
    {
      id: "next-deployment",
      title: "Production Deployment & Optimizations",
      description: "next/image optimization, custom font loading, Core Web Vitals, and edge delivery.",
      docsHref: "/docs/nextjs/deployment",
      type: "primary",
      level: "advanced",
      sectionId: "production",
      keyConcepts: ["next/image AVIF/WebP", "next/font Zero CLS", "Standalone Output Mode"],
    },
  ],
  edges: [
    { source: "next-app-router", target: "next-server-components", type: "primary" },
    { source: "next-server-components", target: "next-client-components", type: "primary" },
    { source: "next-client-components", target: "next-route-handlers", type: "primary" },
    { source: "next-route-handlers", target: "next-server-actions", type: "primary" },
    { source: "next-server-actions", target: "next-caching", type: "primary" },
    { source: "next-caching", target: "next-auth", type: "primary" },
    { source: "next-auth", target: "next-deployment", type: "primary" },
  ],
};
