import type { RoadmapDefinition } from "../types";

export const nodejsRoadmap: RoadmapDefinition = {
  slug: "nodejs",
  title: "Node.js Developer Roadmap",
  subtitle: "Master Asynchronous I/O, Event Loop, Streams, Buffers, Express, and Production Server Architectures",
  description:
    "Complete path to mastering Node.js runtime internals, Streams, Buffers, Worker Threads, REST API frameworks, and production security.",
  category: "language",
  featured: false,
  icon: "server",
  level: "Beginner → Advanced",
  estimatedDuration: "3 - 5 Months",
  relatedRoadmaps: ["backend", "javascript", "typescript", "postgresql", "docker"],
  sections: [
    { id: "runtime", title: "1. Node.js Runtime & Event Loop", order: 1 },
    { id: "core-apis", title: "2. Buffers, Streams & File System", order: 2 },
    { id: "frameworks", title: "3. Express.js & Fastify APIs", order: 3 },
    { id: "performance", title: "4. Clustering, Worker Threads & Profiling", order: 4 },
  ],
  nodes: [
    {
      id: "node-runtime-core",
      title: "Node.js Architecture & Event Loop",
      description: "Libuv thread pool, timers, I/O polling, check phase, and microtask queue priorities.",
      docsHref: "/docs/nodejs/nodejs-overview",
      type: "primary",
      level: "beginner",
      sectionId: "runtime",
      keyConcepts: ["Event Loop Phases", "process.nextTick()", "Non-blocking I/O"],
    },
    {
      id: "node-buffers-streams",
      title: "Buffers, Streams & File Handling",
      description: "Readable, Writable, Transform streams, memory-efficient file uploads, and backpressure.",
      docsHref: "/docs/nodejs/nodejs-overview",
      type: "primary",
      level: "intermediate",
      sectionId: "core-apis",
      keyConcepts: ["Stream Backpressure", "Buffer Allocation", "pipeline() API"],
    },
    {
      id: "node-express-apis",
      title: "Express.js REST APIs & Middleware",
      description: "Custom middleware chains, error handling, CORS, and JSON response formatting.",
      docsHref: "/docs/express/express-overview",
      type: "primary",
      level: "intermediate",
      sectionId: "frameworks",
      keyConcepts: ["Middleware Chaining", "Route Parameters", "Global Error Handling"],
    },
    {
      id: "node-port-collision",
      title: "Debugging Port Conflicts (EADDRINUSE)",
      description: "Diagnosing and killing dangling zombie Node.js background processes.",
      docsHref: "/errors/node/eaddrinuse",
      type: "topic",
      level: "intermediate",
      sectionId: "frameworks",
      keyConcepts: ["lsof -i :port", "kill -9 PID", "Graceful Server Shutdown"],
    },
    {
      id: "node-concurrency",
      title: "Clustering & Worker Threads",
      description: "Utilizing multiple CPU cores with the Cluster module and Worker Threads for CPU tasks.",
      docsHref: "/docs/nodejs/nodejs-overview",
      type: "advanced",
      level: "advanced",
      sectionId: "performance",
      keyConcepts: ["Cluster Module", "Worker Threads", "SharedArrayBuffer"],
    },
  ],
  edges: [
    { source: "node-runtime-core", target: "node-buffers-streams", type: "primary" },
    { source: "node-buffers-streams", target: "node-express-apis", type: "primary" },
    { source: "node-express-apis", target: "node-port-collision", type: "primary" },
    { source: "node-port-collision", target: "node-concurrency", type: "primary" },
  ],
};
