import type { RoadmapDefinition } from "../types";

export const postgresqlRoadmap: RoadmapDefinition = {
  slug: "postgresql",
  title: "PostgreSQL Database Roadmap",
  subtitle: "Master Relational Schema Design, SQL Queries, Indexing, Transactions, and Query Optimization",
  description:
    "Comprehensive guide from SQL basics and table constraints to B-Tree/GIN indexing, ACID transactions, EXPLAIN ANALYZE, and backups.",
  category: "database",
  featured: false,
  icon: "database",
  level: "Beginner → Advanced",
  estimatedDuration: "2 - 4 Months",
  relatedRoadmaps: ["backend", "full-stack", "nodejs"],
  sections: [
    { id: "basics", title: "1. Setup & Relational Tables", order: 1 },
    { id: "queries", title: "2. SQL Queries, Joins & Aggregations", order: 2 },
    { id: "transactions", title: "3. ACID Transactions & Constraints", order: 3 },
    { id: "performance", title: "4. Indexing & Query Optimization", order: 4 },
    { id: "maintenance", title: "5. Backups & Production Administration", order: 5 },
  ],
  nodes: [
    {
      id: "pg-setup-tables",
      title: "Databases, Schemas & Tables",
      description: "Data types (VARCHAR, UUID, JSONB, TIMESTAMP), primary keys, and table creation.",
      docsHref: "/docs/postgresql/tables",
      type: "primary",
      level: "beginner",
      sectionId: "basics",
      keyConcepts: ["UUID vs Serial PKs", "Data Types & Constraints", "CREATE TABLE Syntax"],
    },
    {
      id: "pg-crud-joins",
      title: "CRUD Operations & Relational Joins",
      description: "INNER, LEFT, RIGHT, FULL OUTER JOINs, subqueries, and foreign key relations.",
      docsHref: "/docs/postgresql/joins",
      type: "primary",
      level: "beginner",
      sectionId: "queries",
      keyConcepts: ["INNER vs LEFT JOIN", "Foreign Key Integrity", "GROUP BY & Aggregations"],
    },
    {
      id: "pg-transactions-acid",
      title: "ACID Transactions & Isolation Levels",
      description: "BEGIN, COMMIT, ROLLBACK, Read Committed vs Serializable, and row-level locking.",
      docsHref: "/docs/postgresql/transactions",
      type: "primary",
      level: "intermediate",
      sectionId: "transactions",
      keyConcepts: ["ACID Properties", "Isolation Levels", "SELECT FOR UPDATE"],
    },
    {
      id: "pg-indexes-tuning",
      title: "B-Tree, GIN Indexes & Query Tuning",
      description: "Creating indexes, composite keys, and analyzing queries with EXPLAIN (ANALYZE, BUFFERS).",
      docsHref: "/docs/postgresql/indexes",
      type: "primary",
      level: "advanced",
      sectionId: "performance",
      keyConcepts: ["B-Tree Indexes", "GIN Indexes on JSONB", "EXPLAIN ANALYZE"],
    },
    {
      id: "pg-backup-maintenance",
      title: "pg_dump Backups & Connection Pooling",
      description: "Automating pg_dump, WAL archiving, and PgBouncer connection pooling.",
      docsHref: "/docs/postgresql/backup",
      type: "primary",
      level: "advanced",
      sectionId: "maintenance",
      keyConcepts: ["pg_dump & pg_restore", "PgBouncer Connection Pooling", "VACUUM & Autovacuum"],
    },
  ],
  edges: [
    { source: "pg-setup-tables", target: "pg-crud-joins", type: "primary" },
    { source: "pg-crud-joins", target: "pg-transactions-acid", type: "primary" },
    { source: "pg-transactions-acid", target: "pg-indexes-tuning", type: "primary" },
    { source: "pg-indexes-tuning", target: "pg-backup-maintenance", type: "primary" },
  ],
};
