import type { RoadmapDefinition } from "../types";

export const reactRoadmap: RoadmapDefinition = {
  slug: "react",
  title: "React Developer Roadmap",
  subtitle: "Master component lifecycles, modern hooks, state synchronization, and React 19 architecture",
  description:
    "A deep dive into React 19: from JSX and props to custom hooks, Context API, Suspense, Error Boundaries, and Actions.",
  category: "framework",
  featured: false,
  icon: "code",
  level: "Beginner → Advanced",
  estimatedDuration: "3 - 5 Months",
  relatedRoadmaps: ["frontend", "javascript", "typescript", "nextjs"],
  sections: [
    { id: "foundations", title: "1. React Foundations & JSX", order: 1 },
    { id: "state-effects", title: "2. State Management & Side Effects", order: 2 },
    { id: "advanced-hooks", title: "3. Advanced Hooks & Memoization", order: 3 },
    { id: "architecture", title: "4. Component Composition & Patterns", order: 4 },
    { id: "react-19", title: "5. React 19 Actions & Modern APIs", order: 5 },
  ],
  nodes: [
    {
      id: "react-intro",
      title: "React Overview & Architecture",
      description: "Virtual DOM reconciliation, declarative UI paradigms, and component rendering.",
      docsHref: "/docs/react/introduction",
      type: "primary",
      level: "beginner",
      sectionId: "foundations",
      keyConcepts: ["Declarative UI", "Component Hierarchy", "JSX Syntax"],
    },
    {
      id: "react-components-props",
      title: "Components & Typed Props",
      description: "Functional components, unidirectional data flow, and prop immutability.",
      docsHref: "/docs/react/components",
      type: "primary",
      level: "beginner",
      sectionId: "foundations",
      keyConcepts: ["Props destructuring", "Children prop", "Component purity"],
    },
    {
      id: "react-use-state",
      title: "useState & State Immutability",
      description: "Managing local component state, updater functions, and immutable object/array updates.",
      docsHref: "/docs/react/use-state",
      type: "primary",
      level: "beginner",
      sectionId: "state-effects",
      keyConcepts: ["State Batching", "Functional Updates", "Immutable State"],
    },
    {
      id: "react-use-effect",
      title: "useEffect & Lifecycle Synchronization",
      description: "Synchronizing with external systems, dependency arrays, and cleanup functions.",
      docsHref: "/docs/react/use-effect",
      type: "primary",
      level: "intermediate",
      sectionId: "state-effects",
      keyConcepts: ["Dependency Array Rules", "Cleanup Functions", "Avoiding Infinite Loops"],
    },
    {
      id: "react-use-ref",
      title: "useRef & DOM References",
      description: "Persisting mutable values without triggering re-renders, and accessing DOM nodes.",
      docsHref: "/docs/react/use-ref",
      type: "topic",
      level: "intermediate",
      sectionId: "advanced-hooks",
      keyConcepts: ["Ref vs State", "Focus Management", "Mutable Timers"],
    },
    {
      id: "react-memo-callback",
      title: "useMemo & useCallback",
      description: "Memoizing expensive calculations and stabilizing callback function references.",
      docsHref: "/docs/react/use-memo",
      type: "primary",
      level: "intermediate",
      sectionId: "advanced-hooks",
      keyConcepts: ["Referential Equality", "React.memo()", "Expensive Computations"],
    },
    {
      id: "react-custom-hooks",
      title: "Custom Hooks & Logic Extraction",
      description: "Encapsulating stateful business logic into reusable custom hook functions.",
      docsHref: "/docs/react/custom-hooks",
      type: "primary",
      level: "intermediate",
      sectionId: "architecture",
      keyConcepts: ["Hook Composition", "Rules of Hooks", "Reusable Logic"],
    },
    {
      id: "react-context",
      title: "Context API & Global State",
      description: "Avoiding prop drilling, creating typed Context providers, and consumers.",
      docsHref: "/docs/react/context",
      type: "primary",
      level: "intermediate",
      sectionId: "architecture",
      keyConcepts: ["createContext", "useContext", "Provider Value Memoization"],
    },
    {
      id: "react-data-fetching",
      title: "Data Fetching & Error Boundaries",
      description: "Async loading states, handling network failures gracefully, and component boundaries.",
      docsHref: "/docs/react/data-fetching",
      type: "primary",
      level: "intermediate",
      sectionId: "architecture",
      keyConcepts: ["Loading States", "Error Boundaries", "Race Conditions"],
    },
    {
      id: "react-performance",
      title: "Performance Basics & Profiling",
      description: "React Developer Tools Profiler, preventing wasted renders, and layout shifts.",
      docsHref: "/docs/react/performance-basics",
      type: "primary",
      level: "advanced",
      sectionId: "react-19",
      keyConcepts: ["Profiler Flamegraphs", "Wasted Renders", "Code Splitting"],
    },
  ],
  edges: [
    { source: "react-intro", target: "react-components-props", type: "primary" },
    { source: "react-components-props", target: "react-use-state", type: "primary" },
    { source: "react-use-state", target: "react-use-effect", type: "primary" },
    { source: "react-use-effect", target: "react-use-ref", type: "primary" },
    { source: "react-use-ref", target: "react-memo-callback", type: "primary" },
    { source: "react-memo-callback", target: "react-custom-hooks", type: "primary" },
    { source: "react-custom-hooks", target: "react-context", type: "primary" },
    { source: "react-context", target: "react-data-fetching", type: "primary" },
    { source: "react-data-fetching", target: "react-performance", type: "primary" },
  ],
};
