import type { RoadmapDefinition } from "../types";

export const typescriptRoadmap: RoadmapDefinition = {
  slug: "typescript",
  title: "TypeScript Language Roadmap",
  subtitle: "Master Static Typing, Generics, Utility Types, Discriminated Unions, and Compiler Architecture",
  description:
    "Comprehensive guide from basic type annotations and interfaces to advanced conditional types, mapped types, discriminated unions, and tsconfig strict mode.",
  category: "language",
  featured: false,
  icon: "code",
  level: "Beginner → Advanced",
  estimatedDuration: "2 - 3 Months",
  relatedRoadmaps: ["frontend", "javascript", "react", "nextjs", "angular", "nodejs"],
  sections: [
    { id: "basics", title: "1. Type Annotations & Interfaces", order: 1 },
    { id: "advanced-types", title: "2. Generics & Discriminated Unions", order: 2 },
    { id: "utility-types", title: "3. Utility Types & Narrowing", order: 3 },
    { id: "tooling", title: "4. Compiler Flags & Strict Mode", order: 4 },
  ],
  nodes: [
    {
      id: "ts-basics-interfaces",
      title: "Type Annotations & Interfaces",
      description: "Primitive types, interfaces vs type aliases, optional properties, and readonly modifiers.",
      docsHref: "/docs/typescript/typescript-overview",
      type: "primary",
      level: "beginner",
      sectionId: "basics",
      keyConcepts: ["Interface vs Type Alias", "Structural Typing", "Readonly & Optional Fields"],
    },
    {
      id: "ts-generics-core",
      title: "Generics & Constraints (<T>)",
      description: "Generic functions, classes, interfaces, generic constraints (T extends object), and defaults.",
      docsHref: "/docs/typescript/typescript-overview",
      type: "primary",
      level: "intermediate",
      sectionId: "advanced-types",
      keyConcepts: ["Generic Functions", "extends Constraint", "Default Type Arguments"],
    },
    {
      id: "ts-unions-narrowing",
      title: "Discriminated Unions & Type Guards",
      description: "Tagged unions for state machines, typeof / instanceof checks, and custom is type predicates.",
      docsHref: "/docs/typescript/typescript-overview",
      type: "primary",
      level: "intermediate",
      sectionId: "advanced-types",
      keyConcepts: ["Discriminated Unions", "Type Narrowing (is)", "Exhaustiveness Checking (never)"],
    },
    {
      id: "ts-utility-types",
      title: "Utility Types (Partial, Pick, Omit)",
      description: "Built-in utility transformations: Partial, Required, Readonly, Record, Pick, Omit, ReturnType.",
      docsHref: "/docs/typescript/typescript-overview",
      type: "primary",
      level: "intermediate",
      sectionId: "utility-types",
      keyConcepts: ["Pick<T, K> & Omit<T, K>", "Record<K, V>", "ReturnType<T> & Parameters<T>"],
    },
    {
      id: "ts-compiler-strict",
      title: "tsconfig.json & Strict Mode",
      description: "strictNullChecks, noImplicitAny, exactOptionalPropertyTypes, and moduleResolution bundling.",
      docsHref: "/docs/typescript/typescript-overview",
      type: "primary",
      level: "advanced",
      sectionId: "tooling",
      keyConcepts: ["strictNullChecks", "noImplicitAny", "Bundler Module Resolution"],
    },
  ],
  edges: [
    { source: "ts-basics-interfaces", target: "ts-generics-core", type: "primary" },
    { source: "ts-generics-core", target: "ts-unions-narrowing", type: "primary" },
    { source: "ts-unions-narrowing", target: "ts-utility-types", type: "primary" },
    { source: "ts-utility-types", target: "ts-compiler-strict", type: "primary" },
  ],
};
